// ==UserScript==
// @name         YouTube Studio Patch Collection
// @version      1.2.0
// @description  Allows for changing of yt.config_ values in YouTube Studio (unofficial update)
// @author       Aubrey Pankow (aubyomori@gmail.com)
// @author       Taniko Yamamoto (kirasicecreamm@gmail.com)
// @author       John Patrick Adem (not an actual author, just placing my name here because i made some changes to this script and i forked it)
// @license      Unlicense
// @downloadURL  https://raw.githubusercontent.com/jpa102/YouTubePatchCollection/main/YouTubeStudioPatchCollection.user.js
// @updateURL    https://raw.githubusercontent.com/jpa102/YouTubePatchCollection/main/YouTubeStudioPatchCollection.user.js
// @match        studio.youtube.com/*
// @icon         https://www.youtube.com/favicon.ico
// @run-at       document-start
// @grant        none
// ==/UserScript==

// Attributes to remove from <html>
const ATTRS = [];

// Regular config keys.
const CONFIGS = {};

// Experiment flags.
const EXPFLAGS = {
	AdstubeByChannel__enable_adstube_follow_on_view_goal: false,
	AdstubeByChannel__enable_comix_traffic_estimates: false,
	AdstubeByChannel__enable_comix_traffic_estimates_for_views_goal: false,
	AdstubeByChannel__enable_cta_promotion_creation: false,
	AdstubeByChannel__enable_cta_promotion_update: false,
	AdstubeByChannel__enable_default_video_selection: false,
	AdstubeByChannel__enable_delinking_for_access_lost_ads_account: false,
	AdstubeByChannel__enable_demographic_targeting: false,
	AdstubeByChannel__enable_demographic_targeting_for_website_visit_goal: false,
	AdstubeByChannel__enable_dma_reporting_links: false,
	AdstubeByChannel__enable_follow_on_views_display: false,
	AdstubeByChannel__enable_goals: false,
	AdstubeByChannel__enable_impressions_estimates: false,
	AdstubeByChannel__enable_manager_onboarding_workflow: false,
	AdstubeByChannel__enable_onboarding_for_account_list_failure: false,
	AdstubeByChannel__enable_promote_again_workflow: false,
	AdstubeByChannel__enable_promotion_creation_date_column: false,
	AdstubeByChannel__enable_promotion_list_filtering: false,
	AdstubeByChannel__enable_promotion_prefix_removal: false,
	AdstubeByChannel__enable_promotion_settings_for_oac: false,
	AdstubeByChannel__enable_v2_goal_descriptions: false,
	AdstubeByChannel__enable_website_goal_estimates: false,
	AdstubeByChannel__enable_website_visit_goal: false,
	AdstubeByChannel__show_radio_button_account_step: false,
	AdstubeByChannel__skip_account_step: false,
	AnalyticsByChannel__enable_jewels_reporting_web: false,
	AnalyticsByChannel__enable_old_city_dimension_join_request: false,
	AnalyticsByChannel__enable_realtime_deep_dive_content_type_filter: false,
	AnalyticsByChannel__enable_saved_analytics_explore_reports: false,
	AnalyticsByChannel__enable_shorts_feed_ads_revenue_source_tooltip: false,
	AnalyticsByChannel__enable_sponsors_only_content_in_deep_dive: false,
	AnalyticsByChannel__remove_allowlist_check_in_hypes_metric: false,
	ContentInspirationByChannel__enable_brainstorm_idea_in_videos_tab: false,
	ContentInspirationByChannel__enable_related_videos: false,
	PodcastsByChannel__enable_audiovision_suggestions: false,
	PodcastsByChannel__enable_highlight_plugin_csi_custom_timeline: false,
	PodcastsByChannel__enable_highlights_clear_selection_button: false,
	PodcastsByChannel__enable_highlights_outline: false,
	PodcastsByChannel__enable_interleaved_outline_transcript: false,
	PodcastsByChannel__enable_wiz_ytve_video_highlight_toolbar: false,
	StudioWebHatsByGaia__enable_cms_album_survey: false,
	StudioWebHatsByGaia__enable_cms_videos_survey: false,
	VideoEditorByChannel__enable_new_trim_style: false,
	VideoEditorByChannel__enable_updated_ineligibility_messages_launch: false,
	WebFEAllAdstubeByChannel__disable_end_date_modification_for_website_visit_goal: false,
	WebFEAllAdstubeByChannel__enable_advanced_search_in_interest_targeting: false,
	WebFEAllAdstubeByChannel__enable_eu_blocking_modal: false,
	WebFEAllAdstubeByChannel__enable_eu_political_content_selector_for_promotion_creation: false,
	WebFEAllAdstubeByChannel__enable_eu_political_content_selector_for_promotion_updates: false,
	WebFEAllAdstubeByChannel__enable_improved_disapproval_guidance: false,
	WebFEAllAdstubeByChannel__enable_interest_targeting: false,
	WebFEAllAdstubeByChannel__enable_interest_targeting_for_views_goal: false,
	WebFEAllAdstubeByChannel__enable_location_targeting: false,
	WebFEAllAdstubeByChannel__enable_multi_ad_promotion: false,
	WebFEAllAdstubeByChannel__enable_multi_ad_promotion_migration_for_read: false,
	WebFEAllAdstubeByChannel__enable_promote_after_upload: false,
	WebFEAllAdstubeByChannel__enable_promote_again_workflow_for_details_page: false,
	WebFEAllAdstubeByChannel__enable_promotion_filter_in_unlink_dialog: false,
	WebFEAllAdstubeByChannel__enable_shorts_preview: false,
	WebFEAllAdstubeByChannel__enable_support_for_deleted_promotion: false,
	WebFEAllAdstubeByChannel__enable_video_description_as_promotion_description: false,
	WebFEAllAdstubeByChannel__enable_video_selection_improvements: false,
	WebFEAllAnalyticsByChannel__enable_ad_status_breakdown: false,
	WebFEAllAnalyticsByChannel__enable_ad_status_breakdown_dimension_for_shopping_revenue_metrics: false,
	WebFEAllAnalyticsByChannel__enable_ad_status_filter: false,
	WebFEAllAnalyticsByChannel__enable_collabs_subscribers_channel_name: false,
	WebFEAllAnalyticsByChannel__enable_jewels_reporting_for_canada_web: false,
	WebFEAllAnalyticsByChannel__enable_jewels_reporting_web_for_taiwan: false,
	WebFEAllAnalyticsByChannel__enable_merchant_breakdown_in_yta: false,
	WebFEAllAnalyticsByChannel__enable_primetime_program_grouping: false,
	WebFEAllAnalyticsByChannel__enable_yta_read_gift_analytics_feature_bit_web: false,
	WebFEAllContentInspirationByChannel__enable_animated_loading_status: false,
	WebFEAllContentInspirationByChannel__enable_brainstorm_in_ask_studio: false,
	WebFEAllContentInspirationByChannel__enable_save_toggle_button: false,
	WebFEAllContentInspirationByChannel__skip_summary_generation: false,
	WebFEAllCopyrightByChannel__enable_content_detection_leftnav_name: false,
	WebFEAllCopyrightByChannel__enable_copyright_cc_feature: false,
	WebFEAllCopyrightByChannel__enable_copyright_school_v2_web: false,
	WebFEAllCopyrightByChannel__enable_hats_for_likeness_onboarding: false,
	WebFEAllCopyrightByChannel__enable_likeness_autofill_by_user: false,
	WebFEAllCopyrightByChannel__enable_likeness_filter_by_video: false,
	WebFEAllCopyrightByChannel__enable_likeness_m5: false,
	WebFEAllCopyrightByChannel__enable_likeness_public_figures: false,
	WebFEAllCopyrightByChannel__enable_likeness_takedown_contact_form_regrouping: false,
	WebFEAllCopyrightByChannel__enable_likeness_v2_agreement: false,
	WebFEAllCopyrightByChannel__enable_livestream_urls_on_webform: false,
	WebFEAllCopyrightByChannel__enable_music_generation_on_home_page: false,
	WebFEAllFamebitByChannel__enable_creator_initiated_linking_copy_changes_web: false,
	WebFEAllFamebitByChannel__enable_creator_initiated_linking_on_web: false,
	WebFEAllFamebitByChannel__enable_eu_paid_political_content_checkbox: false,
	WebFEAllLiveStreamingByChannel__disable_processing_message_for_deferred_live_archival: false,
	WebFEAllLiveStreamingByChannel__enable_dual_stream_toggle: false,
	WebFEAllLiveStreamingByChannel__enable_lcr_ads_settings_infobox_fix: false,
	WebFEAllLiveStreamingByChannel__enable_lcr_webcam_header_actions: false,
	WebFEAllLiveStreamingByChannel__enable_live_streaming_consistency_token_jars: false,
	WebFEAllLiveStreamingByChannel__enable_multi_aspect_1p_client_crop_in_lcr: false,
	WebFEAllLiveStreamingByChannel__enable_tns_signals_collection_for_live_creation_lcr: false,
	WebFEAllLiveStreamingByChannel__enable_webcam_go_live_stuck_fix: false,
	WebFEAllLiveStreamingByChannel__enable_webcam_unmute_on_screenshare_fix: false,
	WebFEAllLiveStreamingByChannel__enable_webrtc_transport_reconnect: false,
	WebFEAllPartnerprogramByChannel__enable_expanded_adsense_cooldown: false,
	WebFEAllPartnerprogramByChannel__enable_playable_adsense_settings_desktop: false,
	WebFEAllShoppingByChannel__creator_wiz_experiment_ytshopping_product_details: false,
	WebFEAllShoppingByChannel__creator_wiz_shopping_cow_workshop_components: false,
	WebFEAllShoppingByChannel__deprecate_suggested_filter_chip_in_product_picker: false,
	WebFEAllShoppingByChannel__enable_two_step_timestamp_flow: false,
	WebFEAllStudioByChannel__disable_viewer_posts_new_badge_and_blue_dot: false,
	WebFEAllStudioByChannel__enable_appeal_verification_web: false,
	WebFEAllStudioByChannel__enable_ato_cleanup_v2_fe: false,
	WebFEAllStudioByChannel__enable_auto_dubbing_opt_out_hats_channel_data: false,
	WebFEAllStudioByChannel__enable_auto_dubbing_opt_out_hats_survey: false,
	WebFEAllStudioByChannel__enable_channel_guidelines_string_update: false,
	WebFEAllStudioByChannel__enable_creator_chat_for_generalist: false,
	WebFEAllStudioByChannel__enable_creator_chat_renderer: false,
	WebFEAllStudioByChannel__enable_creator_chat_streaming_panel: false,
	WebFEAllStudioByChannel__enable_creator_chat_streaming_response: false,
	WebFEAllStudioByChannel__enable_creator_experiment_ui_v2: false,
	WebFEAllStudioByChannel__enable_highlight_suggestions_left_side_panel: false,
	WebFEAllStudioByChannel__enable_ipos_appeals_playback: false,
	WebFEAllStudioByChannel__enable_named_subtitles_show_row_fix: false,
	WebFEAllStudioByChannel__enable_new_ui_for_title_component: false,
	WebFEAllStudioByChannel__enable_non_blocking_prechecks_loading: false,
	WebFEAllStudioByChannel__enable_screen_manager_for_command_handler: false,
	WebFEAllStudioByChannel__enable_sidekick_safe_img_renderer: false,
	WebFEAllStudioByChannel__enable_sidekick_thumbnail_feedback_dialog: false,
	WebFEAllStudioByChannel__enable_studio_ingested_tv_show_ff: false,
	WebFEAllStudioByChannel__enable_suggestions_hats_survey: false,
	WebFEAllStudioByChannel__enable_video_files_dialog_in_studio: false,
	WebFEAllStudioByChannel__enable_video_hosted_post_creation_in_studio: false,
	WebFEAllStudioByChannel__enable_viewer_posts_edu: false,
	WebFEAllStudioByChannel__enable_viewer_posts_new_badge_and_blue_dot: false,
	WebFEAllStudioByGaia__creator_wiz_experiment_ytcp_dub_publication_settings: false,
	WebFEAllStudioByGaia__creator_wiz_experiment_ytcp_header: false,
	WebFEAllStudioByGaia__creator_wiz_experiment_ytcp_sam_chat: false,
	WebFEAllStudioByGaia__creator_wiz_experiment_ytshopping_channel_section: false,
	WebFEAllStudioByGaia__creator_wiz_experiment_yttou_guided_resolution: false,
	WebFEAllStudioByGaia__creator_wiz_experiment_ytve_video_highlight_suggestions: false,
	WebFEAllStudioByGaia__enable_apply_channel_spotlight_restrictions: false,
	WebFEAllStudioByGaia__enable_creator_polymer_stvs: false,
	WebFEAllStudioByGaia__enable_mss_lazy_loading: false,
	WebFEAllStudioByGaia__enable_stickiness_script_minified: false,
	WebFEAllStudioByGaia__enable_studio_client_unification_base_module: false,
	WebFEAllStudioByGaia__enable_studio_client_unification_css_mods: false,
	WebFEAllStudioByGaia__enable_studio_renderers_theme_switch_reload: false,
	WebFEAllStudioByGaia__include_invitee_in_video_collaborations_invitation_url: false,
	WebFEAllStudioByGaia__load_studio_extensions_module: false,
	WebFEAllStudioByGaia__publishing_wiz_migration_batch_one: false,
	ab_det_apm: false,
	ab_det_el_h: false,
	action_companion_center_align_description: false,
	add_superfans_to_creator_decoration: false,
	adstube_account_creation: false,
	adstube_account_selection: false,
	adstube_async_account_calls: false,
	adstube_brandx_escape_hatch: false,
	adstube_configs: false,
	adstube_feature_eligibility: true,
	adstube_incentives: true,
	adstube_settings: true,
	allow_ab_experiment_deletion_while_autogens_pending: false,
	allow_skip_networkless: true,
	altered_content_bulk_edits: false,
	att_web_record_metrics: false,
	attmusiw: true,
	bcx_coexistence: false,
	block_audioswap_undo: false,
	cms_remember_viewing_mode: true,
	cms_wiz_migration_batch_three: false,
	cms_ytv_content_performance_daily_report: false,
	compress_gel: false,
	console_log_js_exceptions: false,
	cow_optimize_idom_compat: false,
	creator_enable_dark_theme_in_account_menu: true,
	creator_enable_hide_your_channel_in_suspended_account_menu: false,
	creator_wiz_experiment_ytshopping: true,
	csi_on_gel: true,
	csstrfr: true,
	dark_launch_ypp_benefits_for_ms1_desktop: false,
	delay_sheet_open_killswitch: true,
	disable_child_node_auto_formatted_strings: false,
	disable_log_to_visitor_layer: true,
	disable_pacf_logging_for_memory_limited_tv: true,
	disable_starred_tracks_migration: false,
	embeds_desktop_enable_volume_slider: true,
	enable_1p_product_level_sales_reporting_web: false,
	enable_a11y_focus_fix_for_mac_panel_on_desktop: true,
	enable_aadc_warning: false,
	enable_aadc_warning_global: false,
	enable_access_code_service_rpc: false,
	enable_active_view_display_ad_renderer_web_home: false,
	enable_ad_break_overlay: false,
	enable_additional_info_in_confirm_interest_dialog: false,
	enable_ads_m4: false,
	enable_ads_video_linking_ui: true,
	enable_affiliate_tiered_bonus_progress_tracker: false,
	enable_age_asssurance_message: true,
	enable_artist_studio_concerts_dma_removal: false,
	enable_ask_studio_filter: false,
	enable_audit_record_for_video_linking: false,
	enable_auto_chapter_bulk_edit: false,
	enable_auto_dub_channel_settings: false,
	enable_auto_dub_channel_settings_ypp_early_access: true,
	enable_auto_dub_channel_settings_ypp_early_access_expansion: true,
	enable_auto_dub_channel_settings_ypp_info_default_on: true,
	enable_auto_dubbing_satisfaction_survey_in_studio_web_language_page: true,
	enable_auto_learning_concepts_opt_out: true,
	enable_automotive_form_factor_check: true,
	enable_bcx_auto_ppp: false,
	enable_bcx_multi_video_upload: true,
	enable_bcx_rename: true,
	enable_capi_for_media_kit_customization: true,
	enable_channel_business_email_for_bcx_lite_offer_confirm_interest_dialog: true,
	enable_channel_comment_guidelines_tns_safe: true,
	enable_channel_guidelines_expansion: true,
	enable_channel_pdg_data_fetch: true,
	enable_channel_pfl_contract_bto_flow_studio: false,
	enable_channel_pronouns_on_web_studio: true,
	enable_channel_settings_reauth: false,
	enable_chat_support_shortcut_expansion: false,
	enable_child_panels: false,
	enable_client_only_wiz_tooltips: true,
	enable_client_sli_logging: false,
	enable_client_streamz_web: false,
	enable_client_ve_spec: false,
	enable_cls_force_enable_all_ads_format: false,
	enable_command_handler_screen_manager: false,
	enable_comment_settings_on_off_button_style: false,
	enable_comments_bulk_actions_m2: false,
	enable_comments_published_bulk_actions: false,
	enable_community_section_title_via_comments: false,
	enable_contact_email_prefill: false,
	enable_content_inspiration_3_0: false,
	enable_content_inspiration_4_0: false,
	enable_course_and_podcast_tabs_on_deep_dive: false,
	enable_creator_chat_entry_point_button_on_dashboard_page: false,
	enable_creator_chat_feature_tour: false,
	enable_creator_chat_ghats: false,
	enable_creator_community_moderation_settings_new_ui: false,
	enable_creator_music_track_generation: false,
	enable_creator_pause_comments_setting: true,
	enable_creator_who_can_comment_setting: true,
	enable_creator_wiz_experiment_critical_apis_m1: true,
	enable_dai_sdf_h5_preroll: false,
	enable_datasync_id_header_in_web_vss_pings: false,
	enable_default_mono_cta_migration_web_client: false,
	enable_display_contracts_hub_signed_bcx_contracts: true,
	enable_dubbing_asr_on_web: true,
	enable_early_access_creators_allowlist: true,
	enable_eating_disorder_and_malicious_clickbait: true,
	enable_editing_progress: true,
	enable_education_metadata_type_v2_migration: false,
	enable_enhanced_advanced_mode_m1: true,
	enable_entity_store_from_dependency_injection: false,
	enable_expanded_audience_interests: false,
	enable_famebit_bcx_lite_ui: false,
	enable_famebit_bcx_m1_offer_rejection_survey: false,
	enable_famebit_business_contact_input: false,
	enable_famebit_creator_rate_card_v2: false,
	enable_famebit_flow_logging: false,
	enable_famebit_onboarding_creator_preference_cta: false,
	enable_famebit_onboarding_dashboard_tour: false,
	enable_fan_community_studio_comments_content_type_filter: false,
	enable_fan_shorts_for_creators_in_studio: false,
	enable_fanzone_properties_in_lcr: false,
	enable_follow_up_comments_filter: false,
	enable_google_hats_analytics: true,
	enable_guided_resolution_blocks: true,
	enable_guided_resolution_flow: true,
	enable_halftime_lsam_validation_lcr: false,
	enable_handles_account_menu_switcher: true,
	enable_handles_everywhere: true,
	enable_hide_edit_video_for_alc: false,
	enable_hide_moderated_elq_comments: false,
	enable_i18n_pronouns_editing: true,
	enable_illustration_refresh: true,
	enable_inclusive_gender: true,
	enable_inline_edit_processing_eta: false,
	enable_inline_muted_playback_on_web_search: false,
	enable_inline_muted_playback_on_web_search_for_vdc: false,
	enable_inline_muted_playback_on_web_search_for_vdcb: false,
	enable_lcr_button_renderer_modernization: false,
	enable_lcr_emoji_fountain: false,
	enable_lcr_minor_dialog: false,
	enable_lcr_modernization_phase_1: false,
	enable_lifa_h5_campaign_launch: false,
	enable_likeness_scaled_onboarding: false,
	enable_live_ad_settings_update: false,
	enable_live_ads_hats_survey: false,
	enable_live_archival_eta: false,
	enable_live_chat_moderation_strict: false,
	enable_live_midroll_defaults_ptc: false,
	enable_live_reactions_studio: false,
	enable_livestream_reauth: false,
	enable_loyalty_state: false,
	enable_ltc_param_fetch_from_innertube: false,
	enable_lwe_web_mute: false,
	enable_managing_moderators_ui: true,
	enable_media_kit_hhi_parental_cards: true,
	enable_mentions_creation_tooltip: true,
	enable_metadata_editor_after_audio_upload: true,
	enable_mfk_and_strike_check_for_viewer_posts: false,
	enable_mixed_direction_formatted_strings: false,
	enable_most_relevant_by_default: true,
	enable_ms2_for_all_channels_desktop: false,
	enable_multi_track_deepdive: true,
	enable_multi_track_filter_deepdive: true,
	enable_multi_track_geo: true,
	enable_mweb_keyboard_shortcuts: true,
	enable_names_handles_account_switcher: true,
	enable_new_content_inspiration_tab_name: false,
	enable_new_iph_open_to_gse_flow_sam: false,
	enable_new_self_termination_notification_text: false,
	enable_new_shield_moderator_badge: false,
	enable_nitrate_studio_web_dialog: false,
	enable_non_compliant_tagged_products_video_filter: false,
	enable_non_concurrent_lsam_messaging: false,
	enable_onv_custom_thumbnails_feature_fetch: true,
	enable_open_in_new_tab_icon_for_short_dr_for_desktop_search: true,
	enable_pause_ads_on_ytv_html5: false,
	enable_pdg_canonical_eligibility_studio_desktop: false,
	enable_pdg_gift_experience_creator_studio_web: false,
	enable_permission_switch_reauth: false,
	enable_permissions_management_tour: false,
	enable_pfl_contract_flow_cms_cla: false,
	enable_pfl_contract_flow_studio: false,
	enable_player_for_education_revenue: false,
	enable_player_for_learning_in_earn_hub: false,
	enable_player_for_learning_signing_in_agreements: false,
	enable_playlist_courses_filter: false,
	enable_playlist_translations: false,
	enable_playlist_view_count_and_filters: false,
	enable_podcast_shows_feature_checks: false,
	enable_polymer_resin: false,
	enable_polymer_resin_migration: false,
	enable_posts_advanced_tier_external_links_restriction: false,
	enable_posts_comments_moderation_settings: false,
	enable_prechecks_as_a_platform: false,
	enable_prechecks_notifications: false,
	enable_premiere_intro_studio_flow: false,
	enable_privacy_warning_dialog: false,
	enable_product_tagging_video_filters: false,
	enable_province_for_non_us_countries: false,
	enable_pv_screen_modern_text: false,
	enable_read_only_captions: false,
	enable_reduced_step_grf_desktop: false,
	enable_reduced_step_grf_improvements_desktop: false,
	enable_rejection_reason_payment_info: false,
	enable_remix_dimension_deepdive: false,
	enable_rfa_verification_for_playlist_web_creator: false,
	enable_rto_deprecation: false,
	enable_rto_dialog_change: false,
	enable_screen_manager_layer_separation: false,
	enable_sdf_companion_h5: false,
	enable_sdf_dai_h5_midroll: false,
	enable_sdf_h5_endemic_mid_post_roll: false,
	enable_sdf_on_h5_unplugged_vod_midroll: false,
	enable_sdf_shorts_player_bytes_h5: false,
	enable_self_certification_v15: false,
	enable_self_termination_appeal_pending_review: false,
	enable_shadydom_free_scoped_query_methods: false,
	enable_show_last_update_date_delayed_eligibility_ui: false,
	enable_sidekick_entry_chips_on_community_page: false,
	enable_sidekick_entry_chips_on_yta_page: false,
	enable_simplified_ads_control_desktop: false,
	enable_simplified_ads_control_for_live: false,
	enable_skip_ad_guidance_prompt: false,
	enable_skippable_ads_for_unplugged_ad_pod: false,
	enable_smarter_replies: false,
	enable_smarter_replies_guf: false,
	enable_smearing_expansion_dai: false,
	enable_social_proof_v1: false,
	enable_social_suggestions_dropdown_refit: false,
	enable_storefront_music_assistant: false,
	enable_stream_revoked_string_update: false,
	enable_studio_clips_management_actions: false,
	enable_studio_clips_remove_action: false,
	enable_studio_comments_ranking: false,
	enable_studio_comments_ranking_at_content_level: false,
	enable_studio_dashboard_super_thanks_chip: false,
	enable_studio_top_viewer_posts_feed: false,
	enable_studio_video_clips_list: false,
	enable_thumbnail_ab_experiment_finish_time_estimation: false,
	enable_thumbnail_experiment_stop_and_set: false,
	enable_thumbnail_experiment_video_list: false,
	enable_thumbnail_experiment_wt_tooltip: false,
	enable_tlcs_in_studio: false,
	enable_top_voted_playlist_sorting: false,
	enable_torso_premium_ms2_desktop: false,
	enable_torso_remix_owner_opt_out: false,
	enable_variable_timeout_web: false,
	enable_video_breakdown_on_affiliate_kmc_detail: false,
	enable_video_display_compact_button_group_for_desktop_search: false,
	enable_video_highlights_in_clips: false,
	enable_video_linking_filter_web: false,
	enable_video_states_onboarding_banner_web: false,
	enable_video_states_revamp_m1_earn_hub_update: false,
	enable_video_states_revamp_revenue_column: false,
	enable_video_states_revamp_web: false,
	enable_viewer_posts_feed: true,
	enable_views_in_playlist_breakdown: true,
	enable_violative_video_deletion_warning: false,
	enable_visual_remix_opt_out: true,
	enable_web_cph_outreach: false,
	enable_web_delhi_icons: false,
	enable_web_home_top_landscape_image_layout_level_click: false,
	enable_web_optional_price: true,
	enable_web_tiered_gel: false,
	enable_web_tos_removal: false,
	enable_webcam_canvas_rendering: false,
	enable_webcam_reconnect_in_lcr: false,
	enable_webcam_screen_share: false,
	enable_wiz_queue_effect_and_on_init_initial_runs: false,
	enable_ypp_ad_blocking: true,
	enable_ypp_age_verification: false,
	enable_ypp_ghat_survey: false,
	enable_ypp_midroll_revamp_data_fragment_gaia: false,
	enable_ypp_midroll_revamp_gaia: false,
	enable_ypp_midroll_revamp_video_filter_gaia: false,
	enable_ypp_next_ms2_desktop: false,
	enable_ypp_next_ms2_signup_desktop: false,
	enable_yt_ata_iframe_authuser: false,
	enable_ytbc_bcx_onboarding: false,
	enable_zero_prefix_mention_suggestion_web: false,
	encrypt_actual_user_data_enabled: true,
	export_networkless_options: true,
	export_player_version_to_ytconfig: true,
	fill_single_video_with_notify_to_lasr: false,
	h5_companion_enable_adcpn_macro_substitution_for_click_pings: false,
	h5_inplayer_enable_adcpn_macro_substitution_for_click_pings: false,
	h5_reset_cache_and_filter_before_update_masthead: false,
	handles_in_mention_suggest_posts: false,
	high_ccv_client_side_caching_h5: false,
	html5_log_trigger_events_with_debug_data: false,
	html5_ssdai_enable_media_end_cue_range: false,
	idb_immediate_commit: false,
	il_attach_cache_limit: false,
	il_use_view_model_logging_context: false,
	is_browser_support_for_webcam_streaming: false,
	is_browser_supported_for_live_studio_streaming: false,
	json_condensed_response: false,
	kevlar_gel_error_routing: false,
	kevlar_move_theme_action_handlers_killswitch: false,
	kevlar_use_wil_icons: true,
	killswitch_toggle_button_behavior_resolve_command: false,
	limit_ytcsi_debug_array_size: false,
	live_chat_cow_visibility_set_up: false,
	live_chat_enable_close_for_ticker_item: false,
	live_chat_enable_rta_manager: false,
	live_chat_gifts_on_classic_web: false,
	live_chat_prune_all_participants_char_map: false,
	live_chat_relocate_web_banner_update: false,
	live_chat_require_space_for_autocomplete_emoji: false,
	live_chat_web_use_emoji_manager_singleton: false,
	live_streaming_enable_sink_wrapper: false,
	log_click_with_layer_from_element_in_command_handler: false,
	log_gel_compression_latency: false,
	log_heartbeat_with_lifecycles: false,
	log_unicorn_pages: false,
	mentions_inbox: false,
	migrate_remaining_web_ad_badges_to_innertube: false,
	mweb_account_linking_noapp: false,
	mweb_enable_click_to_play_pause: false,
	mweb_enable_fine_scrubbing_for_recs: false,
	mweb_enable_more_chunks: false,
	mweb_player_control_on_hover: false,
	mweb_progress_bar_seek_on_mouse_click: false,
	mweb_shorts_comments_panel_id_change: false,
	opt_in_creator_email_in_monetization_signup: false,
	opt_in_creator_email_option_enable_by_default: false,
	pageid_as_header_web: false,
	pbcm_fi_inject_decorators: false,
	pbcm_fi_listen_decorators: false,
	pbcm_fi_query_decorators: false,
	pdg_enable_creator_goals_animations: false,
	personalized_auto_mid_roll_card: false,
	player_controls_volume_controls_use_player_props: false,
	polymer_bad_build_labels: false,
	polymer_verifiy_app_state: false,
	prechecks_notifications_optin_via_settings: false,
	propagate_consistency_tokens_from_lcr_to_innertube: false,
	propagate_consistency_tokens_from_studio_web_to_innertube: false,
	public_launch_ypp_benefits_for_ms1_desktop: false,
	qoe_send_and_write: false,
	record_app_crashed_web: false,
	remove_chevron_from_ad_disclosure_banner_h5: false,
	remove_eval_cache: false,
	remove_masthead_channel_banner_on_refresh: false,
	remove_slot_id_exited_trigger_for_dai_in_player_slot_expire: false,
	rename_community_tab_to_posts_tab: false,
	restudio_hagrid_permissions: false,
	restudio_hagrid_sensitive: false,
	return_404_if_delegation_is_missing: false,
	shell_load_gcf: false,
	show_ab_titles_in_title_field: false,
	smarter_ve_dedupping: false,
	sponsorships_desktop_dynamic_peers: false,
	sponsorships_enable_creator_incentives: false,
	sponsorships_enable_early_access_web_shared: false,
	sponsorships_enable_facepile_on_desktop: false,
	sponsorships_perk_first_onboarding_flow_on_desktop_m2: false,
	stop_handling_click_for_non_rendering_overlay_layout: false,
	studio_web_enable_community_creator_heart_rendering_on_posts: false,
	suppress_error_204_logging: false,
	transport_use_scheduler: false,
	use_event_time_ms_header: false,
	use_fifo_for_networkless: false,
	use_request_time_ms_header: false,
	use_rta_manager_for_async: false,
	use_session_based_sampling: false,
	use_thumbnail_overlay_time_status_renderer_for_live_badge: false,
	use_updated_smarter_replies_help_link: false,
	vss_final_ping_send_and_write: false,
	vss_playback_use_send_and_write: false,
	web_api_url: false,
	web_button_or_anchor_list_item: false,
	web_button_view_model_non_nullish_data: false,
	web_button_vm_refactor_disabled: false,
	web_bypass_polymer_yt_icon: false,
	web_c3po_yt_image: false,
	web_csi_action_sampling_enabled: false,
	web_dedupe_ve_grafting: false,
	web_disable_chip_view_model_mutation: false,
	web_enable_ab_rsp_cl: false,
	web_enable_arrow_key_navigation_in_dropdown: false,
	web_enable_chunk_prediction: false,
	web_enable_course_icon_update: false,
	web_enable_error_204: false,
	web_enable_safari_button_tabindex_fix: false,
	web_enable_thumbnail_overlay_alignment: false,
	web_gcf_hashes_innertube: false,
	web_hide_your_data_on_automotive: false,
	web_modern_dialogs: false,
	web_monomer_web_component_wrapper_handle_errors: false,
	web_prefetch_preload_video: true,
	web_progress_bar_draggable: true,
	web_tooltip_size_calculation_fix: false,
	web_unified_fetch: false,
	webfe_eats_enabled: false,
	webpo_exit_on_net_err: false,
	wiz_diff_overwritable: true,
	wiz_next_client_ve_parent_fix: false,
	wiz_next_ld_fix_client_ve_spec: false,
	wiz_wrapper_callback_props_fix: false,
	wug_feedback_endpoint_use_its: false,
	wug_networking_gzip_request: false,
	ytpopup_close_sibling_popups_killswitch: false,
	AdstubeByChannel__default_budget_multiplier: 1,
	H5_async_logging_delay_ms: 30000,
	adstube_min_budget_multiplier: 0,
	attention_logging_scroll_throttle: 500,
	log_window_onerror_fraction: 1,
	polymer_property_access_logging_percent: 0,
	web_attention_logging_scroll_throttle: 500,
	web_load_prediction_threshold: 0.3,
	web_navigation_prediction_threshold: 0.1,
	web_system_health_fraction: 1,
	ytidb_transaction_ended_event_rate_limit: 0.02,
	PodcastsByChannel__autocrop_preview_chunk_duration_sec: 60,
	PodcastsByChannel__interleaved_outline_transcript_timeout_ms: 3000,
	WebFEAllStudioByChannel__creator_commentary_audio_commentary_default_volume: -14,
	WebFEAllStudioByChannel__creator_commentary_audio_commentary_max_volume: 0,
	WebFEAllStudioByChannel__creator_commentary_audio_commentary_min_volume: -60,
	WebFEAllStudioByChannel__creator_commentary_audio_content_default_volume: -36,
	WebFEAllStudioByChannel__creator_commentary_audio_content_max_volume: 0,
	WebFEAllStudioByChannel__creator_commentary_audio_content_min_volume: -60,
	adstube_country_prefill_coverage: 95,
	adstube_country_prefill_limit: 5,
	block_audioswap_undo_group_id: 51502774,
	botguard_async_snapshot_timeout_ms: 3000,
	check_navigator_accuracy_timeout_ms: 0,
	compression_disable_point: 10,
	custom_active_view_tos_timeout_ms: 3600000,
	desktop_fountain_emoji_size_px: 20,
	editing_progress_group_id: 51433937,
	enable_alternative_strike_interstitial_format: 0,
	enable_lifa_h5_campaign_card_multi_arm: 1,
	enable_policy_training_language_picker: 0,
	enable_strike_dashboard_cta: 0,
	fix_blur_regions_group_id: 0,
	gel_min_batch_size: 3,
	gel_queue_timeout_max_ms: 300000,
	initial_gel_batch_timeout: 2000,
	live_chat_chunk_rendering: 0,
	live_chat_chunking_qps_threshold: -1,
	live_chat_continuation_expiration_usec: 300000000,
	live_replay_user_edu_tcv_threshold: 0,
	max_body_size_to_compress: 500000,
	max_prefetch_window_sec_for_livestream_optimization: 10,
	maximum_selectable_comments_number_via_bulk_actions: 100,
	merge_trims_on_backend_group_id: 0,
	min_prefetch_offset_sec_for_livestream_optimization: 20,
	network_polling_interval: 30000,
	product_drop_delay_seconds_override: -1,
	rotating_pinned_product_interval_seconds_override: -1,
	rto_deprecation_group_id: 51447102,
	rto_dialog_change_group_id: 51441610,
	scatter_plot_with_color: 0,
	send_config_hash_timer: 0,
	slow_compressions_before_abandon_count: 4,
	web_foreground_heartbeat_interval_ms: 28000,
	web_gel_debounce_ms: 60000,
	web_logging_max_batch: 100,
	web_max_tracing_events: 50,
	web_session_replay_mousemove_interval: 0,
	web_session_replay_scroll_interval: 0,
	web_session_replay_send_after_timeout: 0,
	web_tracing_session_replay: 0,
	wil_icon_max_concurrent_fetches: 9999,
	ytcsi_debug_max_size: 100,
	ytidb_remake_db_retries: 3,
	ytidb_reopen_db_retries: 3,
	WebFEAllContentInspirationByChannel__content_inspiration_idea_conversation_idea_name_prefix: "**Idea Name:**",
	WebFEAllContentInspirationByChannel__content_inspiration_idea_conversation_prototype_prompt: "Act as my brainstorming partner. Help me develop this video idea to make it really my own, and potentially succesful for my channel. Do this by asking me relevant questions, one at a time, about specific angles that will make this broad idea unique to me. When relevant provide your suggestions based on world knowledge and YT data to help develop this idea and make it the best. Keep your answers short! If the response is related to an idea, at the end of your response, add one line in the form of \"**Idea Name:** <idea name>\". The idea is: ",
	WebFEAllStudioByGaia__creator_web_ts_color_version: "v2_0",
	community_guidelines_exit_csat_trigger_id: "exp_exit_t2",
	community_guidelines_submit_csat_trigger_id: "exp_submit_t2",
	creator_music_promoted_featured_collection_id: "RDCLAK5uy_l949GBtnnSCili8i9EQMwFNLBZ_yoA1Cg",
	debug_forced_internalcountrycode: "",
	demo_chat_support_shortcut: "off",
	il_payload_scraping: "",
	live_chat_unicode_emoji_json_url: "https://www.gstatic.com/youtube/img/emojis/emojis-png-15.1.json",
	pdg_creator_studio_super_vod_updates: "rebrand",
	web_client_version_override: "",
	AdstubeByChannel__unsupported_billing_preauth_countries: [
    	"AR",
    	"KR",
    	"TW",
    	"UA",
    	"IN"
    ],
	AnalyticsByChannel__hype_metric_feature_countries: [
    	"AT",
    	"AU",
    	"BE",
    	"BG",
    	"BR",
    	"CA",
    	"CY",
    	"CZ",
    	"DE",
    	"DK",
    	"EE",
    	"ES",
    	"FI",
    	"FR",
    	"GB",
    	"GR",
    	"HR",
    	"HU",
    	"ID",
    	"IE",
    	"IN",
    	"IT",
    	"JP",
    	"KR",
    	"LT",
    	"LU",
    	"LV",
    	"MT",
    	"MX",
    	"NL",
    	"PL",
    	"PT",
    	"RO",
    	"SE",
    	"SI",
    	"SK",
    	"TR",
    	"TW",
    	"US"
    ],
	VideoEditorByChannel__genai_audioswap_enabled_countries: [],
	disabled_locales_in_studio_web: [],
	fan_communities_trusted_tester_channel_ids_list: [
    	"UCHfDu-2EMT3ZTFcciv94nZA",
    	"UCY4zaZeDafBvcma5zXmQFTA",
    	"UCQ_kNfHmd3cJE6tphomNc3g",
    	"UC-wmnW7lct4fVwOKsyBtIiA",
    	"UCkzBGkq9G89KhWjNePFWXsQ",
    	"UCAzsP5G7gJ2SABKr3fnBCpg",
    	"UCyW2bzS1LNRAwYcROulUgkA",
    	"UCKNyP4sCMUOwHVOYzn5MT9w",
    	"UCyanz5S2Mg3vZyMGL90giFA",
    	"UCbh6tnEE3fVJGkkS2rPdC_A",
    	"UC1Q6jAxUD0SmR6Bq2u1wR2g",
    	"UCmSxt_jAYnQxhfK-aB080WQ",
    	"UCAAbz6ZjWv0a8oWsiFzEuWw",
    	"UC7VvxEW_I2UyHScAZJh6Z",
    	"UCXsFpDDp_1O65JzeiB9pp_A",
    	"UCC6AxuO2MjAL--3apFGLuDw",
    	"UCmt9vxi4BET9AcKdbXmag3A",
    	"UCCAa1V4UsOK5kwsgzkvzdEw",
    	"UCEkP0GLsStgYCacNGNtLe0Q",
    	"UCKrPRjNkwPD4yxnBkqkp6YQ",
    	"UCFnSH4WtWY-YFa1HefLP1xQ",
    	"UCb4c8tKRzDL1wGp2lGGpNzA",
    	"UCOLxOm2Pi2rmuvQfnKsFGZQ",
    	"UCb9F1guxTPSBI-TIj1HtoyA",
    	"UCn-OvDql7cgh8mg08am22Bw",
    	"UCRJBLIR5E1bfDmq3kAzRpeg",
    	"UCnZC4bBrLe5rqAkrkOul-ig",
    	"UCXXZgehRtbz2Fopk9iioZfQ",
    	"UCFtRwgDqD7b6CBYTBXU_YYA",
    	"UC31GyoVAjRLLK9Nh4298PzA",
    	"UC0kRw95ZXrERqDPwQPUvzKQ",
    	"UCVQJZE_on7It_pEv6tn-jdA",
    	"UCPxD9pif2FIamjralQYC23g",
    	"UCKKpXkbaGG6b_MXTfjORiMw",
    	"UCMgCvJ3_QahXgvwj6LjOd-w",
    	"UC5_4POQX0WtMhUpRsh-YQhA",
    	"UCDlP9jgPzVMNdWhgnCs6W4w",
    	"UCtmKE2MzgKzxGsxatojgruA",
    	"UC1H1NWNTG2Xi3pt85ykVSHA",
    	"UC6HDXr-sNPnWLF_Q-y3KduA",
    	"UCeeMfDGVTlPzOH_Zx52-tXA",
    	"UCX4auhvsqthZe5Ncdf0xXLA",
    	"UCPfeM2tm3T19uPf8pU3VHLg",
    	"UCq4o0-2ANaIlNf_dPL3rjdw",
    	"UCffWgsCSfy26LmaY-5HcxmQ",
    	"UCN5pKdeobYtejZxLrofwA5A",
    	"UCxJaVA4Tu6oQaHOppbt8qvA",
    	"UC8-zFgoS2x80TuPRDdITBqw",
    	"UCqRkU0Z4V6UjDKnbc5brl8A",
    	"UCAEgbq_B5SI8dB56O8sJfSA",
    	"UCL3IRp9f41q4hu15T3oPFqg",
    	"UCQfXoxuKbcdOx0uJoHBxjHA",
    	"UCw1UfxJnp1HVvh_QzSbGkog",
    	"UCIkf7n5ocGmdcD9h3iAa7WQ",
    	"UCfhrT6yr4ktutFfZUeOuvGg",
    	"UCjQUiJX7ZGFMOqK7oJlEwvg",
    	"UC55Jb99LT3IINRY_g5V6rtA",
    	"UCNJuJfXCKNWu4-VifYixs8A",
    	"UCKKKYE55BVswHgKihx5YXew",
    	"UCbYXZ16DFRxls4c_d0IfU3w",
    	"UCh98_5mGZWMdoUQDn4btU1A",
    	"UCLn2cHAxOdQOBtdVsQe3BYQ",
    	"UC58DpzFfdSKTzpzPw393eiQ",
    	"UCZg86AOTabX3VJQakP305ew"
    ],
	kevlar_command_handler_command_banlist: [],
	live_chat_dynamic_chunking_interval_range: [],
	live_chat_dynamic_chunking_traffic_range: [],
	web_op_signal_type_banlist: [],
	web_tracing_enabled_spans: [
    	"event",
    	"command"
    ],
	studio_system_icons: false
};

class YTP {
    static observer = new MutationObserver(this.onNewScript);

    static _config = {};

    static isObject(item) {
        return (item && typeof item === "object" && !Array.isArray(item));
    }

    static mergeDeep(target, ...sources) {
        if (!sources.length) return target;
        const source = sources.shift();

        if (this.isObject(target) && this.isObject(source)) {
            for (const key in source) {
                if (this.isObject(source[key])) {
                    if (!target[key]) Object.assign(target, { [key]: {} });
                    this.mergeDeep(target[key], source[key]);
                } else {
                    Object.assign(target, { [key]: source[key] });
                }
            }
        }

        return this.mergeDeep(target, ...sources);
    }


    static onNewScript(mutations) {
        for (var mut of mutations) {
            for (var node of mut.addedNodes) {
                YTP.bruteforce();
            }
        }
    }

    static start() {
        this.observer.observe(document, {childList: true, subtree: true});
    }

    static stop() {
        this.observer.disconnect();
    }

    static bruteforce() {
        if (!window.yt) return;
        if (!window.yt.config_) return;

        this.mergeDeep(window.yt.config_, this._config);
    }

    static setCfg(name, value) {
        this._config[name] = value;
    }

    static setCfgMulti(configs) {
        this.mergeDeep(this._config, configs);
    }

    static setExp(name, value) {
        if (!("EXPERIMENT_FLAGS" in this._config)) this._config.EXPERIMENT_FLAGS = {};

        this._config.EXPERIMENT_FLAGS[name] = value;
    }

    static setExpMulti(exps) {
        if (!("EXPERIMENT_FLAGS" in this._config)) this._config.EXPERIMENT_FLAGS = {};

        this.mergeDeep(this._config.EXPERIMENT_FLAGS, exps);
    }
}

window.addEventListener("yt-page-data-updated", function tmp() {
    YTP.stop();
    for (let i = 0; i < ATTRS.length; i++) {
        document.getElementsByTagName("html")[0].removeAttribute(ATTRS[i]);
    }
    window.removeEventListener("yt-page-date-updated", tmp);
});

YTP.start();

YTP.setCfgMulti(CONFIGS);
YTP.setExpMulti(EXPFLAGS);
